# CI345 HW 1 ( 40 pts)

# Name: Azzam Mehdi

Date 4/20/26

### Part A. Python Programming

In [1]:
# Python Programming 

# List and function
# Finish a function to user enter quarterly sales amount.
# Finish a function to display sales
# In main fuction, invoke above functions and show total and average sales
# Show the result as the example

QUARTER = ["Spring", "Summer", "Fall", "Winter"]
           
def main():
    # create a list to hold the sales of four quarters 
    sales = [0.0] * len(QUARTER)

    inputSales(sales)
    
    print('\nDisplay the quarterly sales')
    display(sales)
    
    print('\nDisplay the summary')
    print('Total sales:              $', sum(sales))
    print('Average quarterly sales   $', sum(sales)/len(QUARTER))

# Ask user to enter sales:
def inputSales(sales):
    for i in range(0, len(sales)):
        print('Enter the sales of', QUARTER[i] ,  ' : $' , end = ' ')
        sales[i] = float(input())

# 1) Finish the method here:
def display(sales):
    for i in range(len(sales)):
        print(f'{QUARTER[i]:<10} : ${sales[i]:.2f}')
        
# Invoke 
main()

Enter the sales of Spring  : $ 100
Enter the sales of Summer  : $ 200
Enter the sales of Fall  : $ 300
Enter the sales of Winter  : $ 400

Display the quarterly sales
Spring     : $100.00
Summer     : $200.00
Fall       : $300.00
Winter     : $400.00

Display the summary
Total sales:              $ 1000.0
Average quarterly sales   $ 250.0

### Part B: Game Salary Data  Analysis

In [2]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# limiting the display rows
pd.set_option('display.max_rows', 8)

In [4]:
gameSalary = pd.read_csv('Data\GameSalary.csv')
gameSalary

,ID,Last Name,First Name,Gender,Department,Title,Salary,Performance
0,10000,Aikman,Gary,F,Sound Design,Senior Sound Designer,67000,Average
1,10387,Felser,Cynthia,F,Animation,Lead Animator,80000,Good
2,10552,Leslie,Jean,F,Art,Artist,45250,Average
3,10936,Cusak,Barbara,F,Programming,Programmer,70125,Average
...,...,...,...,...,...,...,...,...
89,26813,Denver,Jan,F,Programming,Programmer,58400,Average
90,26896,Bermont,Thomas,M,Programming,Lead Programmer,120000,Excellent
91,27244,De Maria,Cristi,F,Programming,Programmer,90000,Excellent
92,27474,Elway,William,M,Programming,Programmer,75000,Good

In [5]:
# 2) Show gameSalary number of rows and columns
print("Azzam Mehdi")
df = gameSalary
df.shape

Azzam Mehdi

(93, 8)

In [6]:
# 3) display all column name
print("Azzam Mehdi")

df.columns

Azzam Mehdi

Index(['ID', 'Last Name', 'First Name', 'Gender', 'Department', 'Title',
       'Salary', 'Performance'],
      dtype='object')

In [7]:
names = gameSalary.columns
for name in names:
    print(name)

ID
Last Name
First Name
Gender
Department
Title
Salary
Performance

In [8]:
# 4) show the first three record
print("Azzam Mehdi")

df.head(3)

Azzam Mehdi

,ID,Last Name,First Name,Gender,Department,Title,Salary,Performance
0,10000,Aikman,Gary,F,Sound Design,Senior Sound Designer,67000,Average
1,10387,Felser,Cynthia,F,Animation,Lead Animator,80000,Good
2,10552,Leslie,Jean,F,Art,Artist,45250,Average

In [9]:
# 5) display all column types

df.dtypes

ID              int64
Last Name      object
First Name     object
Gender         object
Department     object
Title          object
Salary          int64
Performance    object
dtype: object

In [10]:
# 6) Change Salary data type to float
gameSalary["Salary"] = gameSalary["Salary"].astype(float)
gameSalary.dtypes

ID               int64
Last Name       object
First Name      object
Gender          object
Department      object
Title           object
Salary         float64
Performance     object
dtype: object

In [11]:
# 7) Use basic info() 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           93 non-null     int64
 1   Last Name    93 non-null     object
 2   First Name   93 non-null     object
 3   Gender       93 non-null     object
 4   Department   93 non-null     object
 5   Title        93 non-null     object
 6   Salary       93 non-null     float64
 7   Performance  93 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 5.9+ KB

In [12]:
# 8) show Salary column summary

df.Salary.describe()

count        93.000000
mean      62346.182796
std       18004.230095
min       35000.000000
25%       50000.000000
50%       60000.000000
75%       70125.000000
max      120000.000000
Name: Salary, dtype: float64

In [30]:
# 9) show mean, min, max of Salary

print(f'Average Salary: ${gameSalary["Salary"].mean():.2f}')
print(f'Lowest Salary: ${gameSalary["Salary"].min():.2f}')
print(f'Highest Salary : ${gameSalary["Salary"].max():.2f}')

Average Salary: $62346.18
Lowest Salary: $35000.00
Highest Salary : $120000.00

In [34]:
# 10) Show Famale Programmer and sorting by using .sort_values(by='Gender')

,ID,Last Name,First Name,Gender,Department,Title,Salary,Performance
0,10000,Aikman,Gary,F,Sound Design,Senior Sound Designer,67000.0,Average
1,10387,Felser,Cynthia,F,Animation,Lead Animator,80000.0,Good
2,10552,Leslie,Jean,F,Art,Artist,45250.0,Average

In [ ]:
# 11) Display Female employees's average salary




print('Average Salary:  $' , format(res,'.2f'))

In [ ]:
# 12) Display Female Programmer's average salary

In [ ]:
# 13) Only diplay three columns: ID, Salary, Performance

In [ ]:
# 14)
# A) Show all Titles name with no duplicate,       
# B) Display the title names as flowing format    

#res = gameSalary['Title'].unique()
res = gameSalary.Title.unique()
print(res)

print('\nTitles')
print('----------')
for name in res:
    print(name)

In [ ]:
# 15) Create a bar chart to compare average Salary by gender. 
# .groupby('')      
# .mean()      
# plot

In [ ]:
# 16)+17) 
# Create a bar chart to compare average Salary by Department. 
# .groupby('')      
# .mean()      
# plot

In [ ]:
# 17) + 18) Show the number of employees for each performance level 
# and create pie chart (and show percentage)

In [ ]:
# 19) + 20) 
# Show the number of employee for each department,
# and sorted by the values from hight to low
# And plot the result as bar chart

#  .groupby('Department') or df.Department.value_counts() 
#  .sort_values(ascending=False)  
#  .plot